### ISSUE TITLE
Pre-Version 13 Pending Change Checklist

### ISSUE THREAD

**Issue by yogilad** [Azure/azure-kusto-dotnet#55]
- [x] Bump + release notes
- [x] Figure out if to drop support for .net core 2.1
- [x]  Delete Linq @ohadbitt 
- [x] Caching ingstion resources in Direct Ingest (@elirandav )
- [x] Add net8 to tools packages

**Comment by AsafMah** [comment]
4. Figure out if to drop support for .net core 2.1
